name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'Temurin'

      - name: Setup env
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

      - name: Android SDK Command-line Tools 설치
        uses: android-actions/setup-android-sdk@v2
        with:
          cmdline-tools: latest
          repositories: |
            build-tools;33.0.0
            platforms;android-33
            platform-tools
            extras;google;m2repository
            extras;android;m2repository

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
