name: Android CI

on:
  push:
    branches: [ "main" ] # main 브랜치에 push될 때 워크플로우 실행
  pull_request:
    branches: [ "main" ] # main 브랜치로 pull request가 생성될 때 워크플로우 실행

jobs:
  build:
    runs-on: ubuntu-latest # 빌드 환경: Ubuntu 최신 버전

    steps:
      - uses: actions/checkout@v3 # Git 저장소 체크아웃

      - name: Set up JDK 11 # JDK 11 설치
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: ' Temurin '

      - name: 환경변수 설정 # Android SDK 환경변수 설정 (ANDROID_SDK_ROOT)
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

      - name: Android SDK Command-line Tools 설치 # Android SDK Command-line Tools 설치
        uses: android-actions/setup-android-sdk@v2
        with:
          cmdline-tools: latest
          repositories: |
            build-tools;33.0.0 # 필요 Build Tools 버전 명시 (프로젝트에 맞게 수정)
            platforms;android-33 # 필요 Android API Level 명시 (프로젝트에 맞게 수정)
            platform-tools
            extras;google;m2repository
            extras;android;m2repository

      - name: Grant execute permission for gradlew # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Gradle Build # Gradle 빌드 실행 (디버그 APK 빌드)
        run: ./gradlew assembleDebug

      - name: Upload Debug APK # 빌드된 Debug APK 파일 Artifacts에 업로드
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk # APK 파일 경로 (프로젝트에 맞게 수정)
